- ci: update to clang 10
versions before 9 fails to compile with the following error
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_tree.h:701:4: error: exception specification of explicitly defaulted move constructor does not match the calculated one

clang 9 fails to link with the following errors
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/cmath:223: undefined reference to `__expf_finite'
src/rendering/swrenderer/drawers/r_draw_rgba.cpp:1120: undefined reference to `__log2_finite'
src/rendering/swrenderer/drawers/r_draw_rgba.cpp:1120: undefined reference to `__log2_finite'
src/rendering/swrenderer/drawers/r_draw_rgba.cpp:1120: undefined reference to `__log2_finite'
src/rendering/swrenderer/plane/r_flatplane.cpp:183: undefined reference to `__log2_finite'
src/rendering/swrenderer/viewport/r_spritedrawer.cpp:174: undefined reference to `__log2_finite'